name: audit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt || true

    - name: Install pip-audit
      run: |
        source venv/bin/activate
        pip install pip-audit

    - name: Run pip-audit and save to file
      run: |
        source venv/bin/activate
        pip-audit -r requirements.txt > audit-report.txt

    - name: Upload audit report
      uses: actions/upload-artifact@v4
      with:
        name: pip-audit-report
        path: audit-report.txt
