name: Auto Update Python Dependencies

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install pip-audit
        run: pip install pip-audit

      - name: Run pip-audit and save to file
        run: |
          pip-audit > audit-report.txt || true

      - name: Commit audit report to repo
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add audit-report.txt
          git commit -m "Add: pip audit report [bot]" || echo "No changes to commit"
          git push
