name: Auto Update Python Dependencies

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install pip-review safety

      - name: Auto-update and scan
        run: |
          pip-review --auto || echo "No updates"
          pip freeze > requirements.txt
          safety check -r requirements.txt > report.txt || echo "Safety check completed"

      - name: Setup GitHub Credentials
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'

      - name: Commit and push changes
        run: |
          git add requirements.txt report.txt
          git commit -m 'Auto updated Python dependencies [bot]' || echo "No changes to commit"
          git push origin main
