name: Auto Update Python Dependencies

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # ✅ THIS IS IMPORTANT for pushing changes

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install tools
        run: |
          pip install pip-review safety

      - name: Auto-update and scan
        run: |
          pip-review --auto
          pip freeze > requirements.txt
          safety check -r requirements.txt > report.txt

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Commit & Push
        run: |
          git add requirements.txt report.txt
          git commit -m "🤖 Auto update dependencies [bot]" || echo "No changes to commit"
          git push origin main
