name: pip-audit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Create and activate virtual environment
        run: |
          python -m venv audit-env
          source audit-env/bin/activate
          pip install --upgrade pip
          pip install pip-audit
          pip-audit -r requirements.txt > audit-report.txt || true

      - name: Commit audit report to repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add audit-report.txt
          git commit -m "Add pip-audit report" || echo "No changes to commit"
          git push || echo "No changes to push"
